[package]
name = "variables"
version = "2.3.4"
edition = "2021"
authors = ["Trevor Roberts Jr <Trevor.Roberts.Jr@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
